SELECT p.NOME, AVG(cap.NOTA) AS MEDIA_DE_AVALIACOES
FROM PRODUTO p, COMPRA_AVALIA_PRODUTO cap, ORDEM_DE_COMPRA o
WHERE p.CODPROD = cap.CODIGO_PRODUTO AND o.CODORDEM = cap.CODIGO_COMPRA AND EXTRACT(YEAR FROM o.DATA_COMPRA) = 2020
  AND EXTRACT(MONTH FROM o.DATA_COMPRA) = 01
GROUP BY p.NOME
HAVING AVG(cap.NOTA) > 7;