SELECT cl.NOME, COUNT(*) AS QUANTIDADE
FROM CLIENTE cl, TRANSPORTADORA t, ORDEM_DE_COMPRA oc
WHERE oc.CODIGO_CLIENTE = cl.CODCLI AND t.CODTRANS = oc.CODIGO_TRANSPORTADORA AND t.CODTRANS = 1
GROUP BY cl.NOME