SELECT *
FROM CLIENTE
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_NASCIMENTO) / 12) > (SELECT AVG(TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_NASCIMENTO) / 12))
                                                              FROM CLIENTE);