SELECT p.NOME, com.QUANTIDADE
FROM PRODUTO p, TRANSPORTADORA t, ORDEM_DE_COMPRA o, COMPRA_PRODUTO com
WHERE o.CODIGO_TRANSPORTADORA = t.CODTRANS AND com.CODIGO_COMPRA = o.CODORDEM AND
com.CODIGO_PRODUTO = p.CODPROD AND p.PRECO_VENDA < 10 AND t.CODTRANS = 1;