SELECT n.CODNF AS COD_NOTA_FISCAL, n.VALOR_TOTAL AS ValorTotal, p.NOME AS NOME_PRODUTO, MAX(com.QUANTIDADE) AS QUANTIDADE
FROM NOTA_FISCAL n, ORDEM_DE_COMPRA o, COMPRA_PRODUTO com, PRODUTO p
WHERE com.CODIGO_COMPRA = o.CODORDEM
AND n.COD_ORDEM_COMPRA = o.CODORDEM
AND com.CODIGO_PRODUTO = p.CODPROD
AND com.QUANTIDADE > 5
AND (com.CODIGO_PRODUTO, com.QUANTIDADE) IN (
    SELECT cp.CODIGO_PRODUTO, MAX(cp.QUANTIDADE)
    FROM COMPRA_PRODUTO cp
    GROUP BY cp.CODIGO_PRODUTO
)
GROUP BY n.CODNF, n.VALOR_TOTAL, p.NOME;