-- DROP CONSTRAINTS
ALTER TABLE COMPRA_AVALIA_PRODUTO DROP CONSTRAINT PRODUTO_AVALIA_FK;
ALTER TABLE COMPRA_AVALIA_PRODUTO DROP CONSTRAINT AVALIA_PRODUTO_FK;
ALTER TABLE COMPRA_AVALIA_PRODUTO DROP CONSTRAINT AVALIA_PRODUTO_PK;
ALTER TABLE COMPRA_PRODUTO DROP CONSTRAINT PRODUTO_COMPRA_FK;
ALTER TABLE COMPRA_PRODUTO DROP CONSTRAINT COMPRA_PRODUTO_FK;
ALTER TABLE COMPRA_PRODUTO DROP CONSTRAINT COMPRA_PRODUTO_PK;
ALTER TABLE NOTA_FISCAL DROP CONSTRAINT CODIGO_ORDEM_DE_COMPRA_FK;
ALTER TABLE NOTA_FISCAL DROP CONSTRAINT NOTA_FISCAL_PK;
ALTER TABLE ORDEM_DE_COMPRA DROP CONSTRAINT CHECK_STATUS;
ALTER TABLE ORDEM_DE_COMPRA DROP CONSTRAINT CODIGO_TRANSPORTADORA_COMPRA_FK;
ALTER TABLE ORDEM_DE_COMPRA DROP CONSTRAINT CODIGO_CLIENTE_COMPRA_FK;
ALTER TABLE ORDEM_DE_COMPRA DROP CONSTRAINT ORDEM_DE_COMPRA_PK;
ALTER TABLE FORNECIMENTO DROP CONSTRAINT CODIGO_FORNECEDOR_FORNECE_FK;
ALTER TABLE FORNECIMENTO DROP CONSTRAINT CODIGO_PRODUTO_FORNECE_FK;
ALTER TABLE FORNECIMENTO DROP CONSTRAINT FORNECEDOR_FORNECE_PRODUTO_PK;
ALTER TABLE PRODUTO DROP CONSTRAINT CODIGO_CATEGORIA_PRODUTO_FK;
ALTER TABLE PRODUTO DROP CONSTRAINT CODIGO_PRODUTO_PK;
ALTER TABLE CATEGORIA DROP CONSTRAINT CATEGORIA_PK;
ALTER TABLE FORNECEDOR DROP CONSTRAINT FORNECEDOR_PK;
ALTER TABLE TRANSPORTADORA DROP CONSTRAINT TRANSPORTADORA_PK;
ALTER TABLE TELEFONES_CLIENTE DROP CONSTRAINT CODIGO_CLIENTE_FK;
ALTER TABLE TELEFONES_CLIENTE DROP CONSTRAINT CLIENTE_TELEFONE_PK;
ALTER TABLE CLIENTE DROP CONSTRAINT CLIENTE_INDICA_FK;
ALTER TABLE CLIENTE DROP CONSTRAINT CLIENTE_PK;

-- DROP TABLES
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TELEFONES_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTADORA CASCADE CONSTRAINTS;
DROP TABLE FORNECEDOR CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE NOTA_FISCAL CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE FORNECIMENTO CASCADE CONSTRAINTS;
DROP TABLE ORDEM_DE_COMPRA CASCADE CONSTRAINTS;
DROP TABLE COMPRA_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE COMPRA_AVALIA_PRODUTO CASCADE CONSTRAINTS;

-- DROP SEQUENCES
DROP SEQUENCE CLIENTE_SEQ;
DROP SEQUENCE TRANSPORTADORA_SEQ;
DROP SEQUENCE FORNECEDOR_SEQ;
DROP SEQUENCE CATEGORIA_SEQ;
DROP SEQUENCE NOTA_FISCAl_SEQ;
DROP SEQUENCE PRODUTO_SEQ;
DROP SEQUENCE ORDEM_DE_COMPRA_SEQ;